### ISSUE TITLE
Crash when editing pad in Footprint Editor

### ISSUE THREAD

**Issue by operativeF** [heikkipu/kicad4devel#2]
Just as the title suggests, there's a crash when I go to edit footprints. I'm running on W10 and applied (rebased) your changes over the newest master. I tried to run a back trace but I was told that I needed a debugger for the python related code it was trying to give information for. Given that, I think it's something to do with python.

**Comment by heikkipu** [comment]
I am using linux and do not make windows builds. If you try with kicad master repo editor, does it happens then? These additions do not have any python code.

**Comment by jano2358** [comment]
I just tried and it crashed too. I'm using it on linux (mint 18.1-kde_5.8.6), uname -a: Linux J-TH 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
I have kicad_4.0.6 from repositories and yours in /usr/local, so usually I run yours from console and after crash in the console I only get a segmentation fault, in the kernel log I have this line: Jun  1 17:15:57 J-TH kernel: [82753.491817] kicad[24319]: segfault at 770 ip 00007f747b2db8cc sp 000000000c3e8570 error 4 in _pcbnew.kiface[7f747ace1000+d6a000]
the only need to provoke the crash was edit any pad on any library from footprint editor, if I edit a random pad from pcbnew it works as should be.
I can collect more info if you need it (and explain me how :))

**Comment by heikkipu** [comment]
Thank you for reporting this. Now it is fixed.
