### ISSUE TITLE
Compile error - 'uint' does not name a type.

### ISSUE THREAD

**Issue by Ripae** [heikkipu/kicad4devel#5]
This version would cross out three items from my (currently) eight point wish list, so I'm more than willing to try it out. However, it does not compile, because there's an undefined type "uint" used in several files.

**Comment by Ripae** [comment]
### Hooray!  Compile succeeded after following mods:

1. From kicad-source-mirror, copy missing files to:
        kicad-devel/include/build_version.h
        kicad-devel/scripting/build_tools/*.*

2. Add following lines to kicad-devel/pcbnew/pcbnew.h (in the lack of better place)
        typedef unsigned int uint;
        typedef unsigned long ulong;

After make install, a quick try-out showed the binary works. Corners got rounded, teardrops emerged and the new menus work alright. I'll try stitching tomorrow.

### Below is a list of files using undefined types "uint " and "ulong"

$ grep -iwrl uint
pcbnew/class_module.cpp
pcbnew/edit.cpp
pcbnew/trackitems/roundedtrackscorner.cpp
pcbnew/trackitems/roundedtrackscorner.h
pcbnew/trackitems/roundedtrackscorners.h
pcbnew/trackitems/roundedtrackscorners_common.cpp
pcbnew/trackitems/roundedtrackscorners_common_menus.cpp
pcbnew/trackitems/roundedtrackscorners_common_misc.cpp
pcbnew/trackitems/roundedtrackscorners_pcbnew.cpp
pcbnew/trackitems/roundedtrackscorners_pcbnew_DRC.cpp
pcbnew/trackitems/teardrop.cpp
pcbnew/trackitems/teardrop.h
pcbnew/trackitems/teardrops.h
pcbnew/trackitems/teardrops_common.cpp
pcbnew/trackitems/teardrops_common_commit.cpp
pcbnew/trackitems/teardrops_common_edit.cpp
pcbnew/trackitems/teardrops_common_misc.cpp
pcbnew/trackitems/teardrops_pcbnew.cpp
pcbnew/trackitems/teardrops_pcbnew_DRC.cpp
pcbnew/trackitems/trackitems.h
pcbnew/trackitems/trackitems_common.cpp
pcbnew/trackitems/trackitems_pcbnew.cpp
pcbnew/trackitems/tracknodeitem.cpp
pcbnew/trackitems/tracknodeitem.h
pcbnew/trackitems/tracknodeitems.h
pcbnew/trackitems/tracknodeitems_common.cpp
pcbnew/trackitems/tracknodeitems_pcbnew.cpp

$ grep -iwrl ulong
pcbnew/trackitems/teardrop.h
pcbnew/trackitems/teardrops_common_edit.cpp

**Comment by heikkipu** [comment]
Sorry using non standard types. gcc just accepts them. I fix them as standard as soon as possible.

**Comment by heikkipu** [comment]
types fixed and added missing files
