### ISSUE TITLE
just a couple of missing files

### ISSUE THREAD

**Issue by jano2358** [heikkipu/kicad4devel#6]
hello!
I was updating today when: 
CMake Error at bitmaps_png/CMakeLists.txt:766 (add_library):
  Cannot find source file:

    cpp_26/add_via.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "bitmaps".
CMake Error: CMake can not determine linker language for target: bitmaps

and:

In file included from /home/jano/kick_ro/kicad-devel/common/footprint_info.cpp:37:0:
/home/jano/kick_ro/kicad-devel/common/../pcbnew/class_module.h:37:28: fatal error: core/iterators.h: No such file or directory
compilation terminated.
common/CMakeFiles/common.dir/build.make:2135: recipe for target 'common/CMakeFiles/common.dir/footprint_info.cpp.o' failed
make[2]: *** [common/CMakeFiles/common.dir/footprint_info.cpp.o] Error 1
CMakeFiles/Makefile2:325: recipe for target 'common/CMakeFiles/common.dir/all' failed
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2

I copy them from the main devel trunk and everything works!

**Comment by heikkipu** [comment]
Hope that all necessary files are there now
