### ISSUE TITLE
several crashes today

### ISSUE THREAD

**Issue by jano2358** [heikkipu/kicad4devel#7]
hi! 

today I compiled the last update and I was experimenting with it, several crashes occurred in GAL or in classic view, here is the report in kern.log:
Aug 27 17:33:09 J-TH kernel: [ 4918.928342] pcbnew[5414]: segfault at 331 ip 0000000000000331 sp 00007ffdb062f848 error 14 in pcbnew[400000+81000]
Aug 27 17:36:13 J-TH kernel: [ 5103.098580] pcbnew[5495]: segfault at b4 ip 00007f9ec813638e sp 00007fffb0166a00 error 4 in _pcbnew.kiface[7f9ec7c8c000+d73000]
Aug 27 17:40:56 J-TH kernel: [ 5386.209233] pcbnew[5936]: segfault at b4 ip 00007f293286c33e sp 00007ffcf5c8c5d0 error 4 in _pcbnew.kiface[7f293236e000+10f3000]

las two are kind of repeatable, let me know if you need some more info
in the first the interface don't die but it delete all my tracks and save this to disk

**Comment by jano2358** [comment]
it crashes more often when I recreate the areas (B) (if this is any clue)

**Comment by heikkipu** [comment]
Hi

ok I try to test area fills.

**Comment by heikkipu** [comment]
Hi

Does it behave better now?

**Comment by jano2358** [comment]
hi!
I will try it later and tell back to you, cheers!

**Comment by jano2358** [comment]
hi!
now it don't delete all my tracks and save the file, which is good :)
I can't make it crash in legacy, but I have a similar failure in OpenGL, I get this on the kern.log: 
Sep  1 20:21:26 J-TH kernel: [236757.432808] kicad[14120]: segfault at 18 ip 00007fbd8740f1b9 sp 0000000003c4b310 error 6 in _pcbnew.kiface[7fbd8692b000+10f4000]
Sep  1 20:23:57 J-TH kernel: [236908.668085] kicad[14209]: segfault at 18 ip 00007f24ee40d1b9 sp 0000000004f67fb0 error 6 in _pcbnew.kiface[7f24ed929000+10f4000]
as you can see I can repeat the procedure and the same happens. I will attach a file with a pcb on it, if it's useful you can try to repeat the procedure by yourself, to make it happens: select all the vias in the left bottom side along with the small tracks, delete them, hit b -> crash.

[crash_test.tar.gz](https://github.com/heikkipu/kicad-devel/files/1271180/crash_test.tar.gz)

I cannot test this in legacy because I can't select multiple vias (don't know if it's possible).

**Comment by heikkipu** [comment]
Hi

I do not have my better computer at the moment. Hoply end of this week I can get it fixed.

**Comment by heikkipu** [comment]
Hi

I am fixing my machine right now. Hopely I can get fixed it for next weekend.

**Comment by heikkipu** [comment]
Machine and this issue fixed. I think.
